### ISSUE TITLE
PA Review: {userAuth}

### ISSUE THREAD

**Issue by georgesco94** [georgesco94/greatReads#15]

**Comment by m1010j** [comment]
I'm getting 500 errors no matter where I click or what I input into the forms. Is it working for you locally?

**Comment by m1010j** [comment]
- [ ] Your auth functionality is great, but you're not rendering your errors yet. Make sure to add that and to style your errors. (But don't spend too much time on rendering the errors!).

- [ ]  It also looks like you may not be validating the presence of an email address when signing up. Is that on purpose?

**Comment by georgesco94** [comment]
No, I completely forgot to validate email presence and render errors, will fix it. Thanks

**Comment by georgesco94** [comment]
Hi Matthias , it should be working now on Heroku as well , let me know if there are other issues.

**Comment by m1010j** [comment]
Looks great now!
