### ISSUE TITLE
PA Review: {Books}

### ISSUE THREAD

**Issue by georgesco94** [georgesco94/greatReads#16]

**Comment by m1010j** [comment]
- [ ] Your infinite scroll should stop fetching when there's nothing more to fetch.

**Comment by m1010j** [comment]
- [ ] Maybe call it 'Add Book' instead of 'Make Book'.

- [ ] When I add a book and attach a cover, the dimensions of the preview are a bit funky.

**Comment by georgesco94** [comment]
Should be fixed now

**Comment by m1010j** [comment]
👍
